export const traeEnterpriseResources = {
  'zh-CN': {
    traeEnterprise: {
      nav: { group: '企业管理（新版）', analysis: '数据分析', members: '人员管理', subscription: '订阅管理', usage: '用量管理', audit: '操作日志' },
      common: { breadcrumb: '企业管理', select: '请选择', search: '搜索', export: '导出', noData: '暂无数据', noDataHint: '当前筛选范围内没有可展示的数据', all: '全部', close: '关闭', confirm: '确定', cancel: '取消', save: '保存', success: '操作成功', loading: '加载中...', today: '今天', refresh: '刷新' },
      memberDialogs: { deleteDepartmentConfirmTitle: '确定删除此部门吗？', deleteDepartmentConfirmHint: '删除后，部门数据将无法恢复。' },
      departmentTable: { people: '部门人数', operation: '操作', detail: '详情', detailTitle: '部门详情', selectCurrent: '选中当前部门', selectBranch: '选择当前及全部下级', moveUp: '上移', moveDown: '下移', deleteBlockedTitle: '请先移除子部门及部门内人员', deleteBlockedHint: '请先移除所有子部门及部门内全部人员后再操作删除。' },
      analysis: {
        title: '数据分析', scope: '选择人员或部门…', picker: { people: '人员', departments: '部门', search: '输入姓名、邮箱搜索', allPeople: '全部人员', allDepartments: '全部部门', collapse: '收起部门', expand: '展开部门' }, datePresets: { last7: '近 7 天', last30: '近 30 天', last90: '近 90 天' }, start: '开始日期', end: '结束日期', export: '导出全部数据', people: '人员数据', total: '总计使用人员数量', ide: 'IDE 使用人员数量', plugin: '插件使用人员数量', cli: 'CLI 使用人员数量', mobile: 'TRAE 移动端使用人员数量', desktop: 'TRAE Work 桌面版使用人员数量', web: 'TRAE Work 网页版使用人员数量', trend: '人员活跃度趋势', core: '核心使用数据', aiRate: 'AI 生成率', generated: 'AI 生成代码量', cue: 'CUE 推荐次数', chatTrend: '对话生成代码趋势', cueTrend: 'CUE 推荐代码趋势', chatGenerated: '生成代码量', chatAccepted: '采纳代码量', cueRecommended: '推荐代码次数', cueAccepted: '采纳代码次数', other: '其他', chartLegend: '图表图例', mcp: 'MCP 排行榜', agent: '企业专属智能体排行榜', models: '大模型调用分布图', languages: '编程语言分布图', tPlusOne: '数据分析更新时间为 T+1', selected: '当前筛选：{{value}}' },
      members: {
        bulkUpload: '批量上传或修改', emailAdd: '邮件添加', linkInvite: '链接邀请',
 title: '人员管理', seats: '总席位数', occupied: '全端账号已占用', workOccupied: 'Work 专属账号已占用', purchase: '增购席位', add: '添加成员', tabs: { people: '企业人员', departments: '部门管理', requests: '申请列表' }, collapseTree: '收起部门树', expandTree: '展开部门树', collapseDepartment: '收起部门', expandDepartment: '展开部门', moreDepartmentActions: '更多部门操作', searchDepartment: '搜索部门', newDepartment: '新建部门', newDepartmentTitle: '新建部门', editDepartmentTitle: '编辑部门', departmentName: '部门名称', departmentNamePlaceholder: '请输入部门名称', departmentID: '部门 ID', parentDepartment: '上级部门', editDepartmentAction: '编辑部门', addChildDepartment: '添加子部门', deleteDepartment: '删除部门', deleteDepartmentSuccess: '部门已删除', totalMembers: '总人数', joinedMembers: '已加入', searchPeople: '搜索人员名称、邮箱', direct: '仅展示部门直属成员', accountType: '全部账号类型', status: '全部状态', requestPending: '待通过', requestRejected: '已拒绝', person: '人员', state: '状态', stateRules: '查看人员状态流转规则', role: '角色', type: '账号类型', joined: '加入席位时间', department: '部门', owner: '管理员', member: '成员', admin: '超级管理员', active: '正常', invited: '待激活', suspended: '已停用', more: '更多操作', edit: '编辑成员', disable: '停用账号', enable: '启用账号', remove: '移除成员', changeDepartment: '变更部门', reclaimAccount: '回收账号', changeRole: '修改角色', switchToWorkAccount: '修改为 Work 专属账号', transferSuperAdmin: '移交超级管理员', removeMember: '移除人员', requestUser: '申请人', requestDepartment: '申请部门', requestTime: '申请时间', requestAction: '处理', approve: '通过', reject: '拒绝', addTitle: '添加成员', email: '邮箱地址', emailPlaceholder: '请输入成员邮箱', roleLabel: '成员角色', addSuccess: '成员邀请已创建', empty: '暂无成员数据', departmentDetail: '管理部门名称、直属成员和组织层级。', directMembers: '直属成员', childDepartments: '下级部门', monthlyRequests: '本月请求', editDepartment: '编辑部门', ruleInvited: '邀请发送后等待成员完成登录和绑定。', ruleActive: '成员可以按照角色权限使用企业资源。', ruleSuspended: '停用后会立即撤销工作空间访问权限。' },
      subscription: {
        title: '订阅管理', goManage: '前往管理', plan: '订阅计划', current: '当前订阅', flagship: '旗舰版', active: '生效中', expiry: '到期时间', renew: '立即续费', seats: '席位', seatHint: '1 席位 → 3 账号名额', addSeats: '增购席位', available: '可用账号', allAccount: '全端账号', workAccount: 'Work 专属账号', remaining: '剩余', addon: '加量包', notPurchased: '暂未购买', buyAddon: '购买加量包', payg: '按量计费', notOpen: '暂未开通', openPayg: '开通按量付费', actionNotice: '已记录“{{action}}”操作，等待后端接入。' },
      usage: {
        title: '用量管理', cycle: '订阅周期：{{start}} 至 {{end}}', tabs: { board: '用量看板', detail: '用量明细' }, overall: '整体用量', base: '基础会话', overage: '超额会话', exhausted: '已用尽', noLimit: '无人均限额', adjust: '调整限额', buy: '购买加量包', noPackage: '暂未购买任何加量包', people: '人员用量', searchPeople: '搜索人员名称、邮箱', allMembers: '全部成员', allAccounts: '全部账号类型', overageFilter: '超额会话用量', departments: '部门用量', searchDepartment: '搜索部门', detailDate: '日期', detailPerson: '人员', detailAccount: '账号类型', detailRequests: '请求次数', detailTokens: 'Token 用量', detailCost: '费用', detailStatus: '状态', detailEmpty: '暂无用量明细', limitTitle: '调整人均限额', limitHint: '设置后将应用于当前企业工作空间。', limitPlaceholder: '请输入限额', buyTitle: '购买加量包', buyHint: '当前为演示状态，后端接入后将跳转真实购买流程。', perMemberLimit: '人均限额', selectAll: '全选', name: '姓名', department: '所属部门', periodTotal: '当前周期总用量（元）', baseAmount: '基础会话用量（元）', overageAmount: '超额会话用量（元）', operation: '操作', detailAction: '用量明细', quotaAction: '修改配额', chooseMember: '选择人员', today: '今天', last7: '近7天', last30: '近30天', custom: '自定义', dateRange: '选择日期范围', download: '下载', downloadSuccess: '下载成功', pagination: '分页', previousPage: '上一页', nextPage: '下一页', rowsPerPage: '每页行数', rowsUnit: '行/页', client: '客户端', model: 'TRAE 内置模型', session: 'Session ID', tokensConsumed: 'Token 消耗', costConsumed: '金额消耗', modelCalls: '模型调用次数', source: '消耗来源', discounted: '折后' },
      usageFilters: { quotaMembers: '单独配额成员', baseLabel: '基础会话用量', all: '全部', normal: '正常　用量低于 90%', warning: '预警　用量介于 90% 至 100%', exhausted: '耗尽　用量达到 100%' },
      audit: {
        title: '操作日志', export: '导出操作日志', type: '全部操作类型', operator: '选择操作人', date: '选择时间范围', time: '操作时间', action: '操作类型', detail: '操作详情', result: '结果', ip: 'IP 地址', success: '成功', failed: '失败', view: '查看详情', empty: '暂无操作日志', detailTitle: '操作详情', detailOperator: '操作人', detailTarget: '操作对象', detailRequest: 'Request ID', close: '关闭' },
    },
  },
  'en-US': {
    traeEnterprise: {
      nav: { group: 'Enterprise (new)', analysis: 'Data analysis', members: 'Members', subscription: 'Subscription', usage: 'Usage', audit: 'Operation log' },
      common: { breadcrumb: 'Enterprise', select: 'Select', search: 'Search', export: 'Export', noData: 'No data', noDataHint: 'No data is available for the current filters.', all: 'All', close: 'Close', confirm: 'Confirm', cancel: 'Cancel', save: 'Save', success: 'Action completed', loading: 'Loading...', today: 'Today', refresh: 'Refresh' },
      memberDialogs: { deleteDepartmentConfirmTitle: 'Delete this department?', deleteDepartmentConfirmHint: 'This action cannot be undone.' },
      departmentTable: { people: 'People', operation: 'Actions', detail: 'Details', detailTitle: 'Department details', selectCurrent: 'Select current department', selectBranch: 'Select department and all children', moveUp: 'Move up', moveDown: 'Move down', deleteBlockedTitle: 'Remove child departments and members first', deleteBlockedHint: 'Remove all child departments and members before deleting this department.' },
      analysis: {
        title: 'Data analysis', scope: 'Select a member or department…', picker: { people: 'People', departments: 'Departments', search: 'Search name or email', allPeople: 'All people', allDepartments: 'All departments', collapse: 'Collapse department', expand: 'Expand department' }, datePresets: { last7: 'Last 7 days', last30: 'Last 30 days', last90: 'Last 90 days' }, start: 'Start date', end: 'End date', export: 'Export all data', people: 'People data', total: 'Total active people', ide: 'IDE active people', plugin: 'Plugin active people', cli: 'CLI active people', mobile: 'TRAE mobile active people', desktop: 'TRAE Work desktop active people', web: 'TRAE Work web active people', trend: 'People activity trend', core: 'Core usage data', aiRate: 'AI generation rate', generated: 'AI generated code', cue: 'CUE recommendations', chatTrend: 'Chat generated code trend', cueTrend: 'CUE recommended code trend', chatGenerated: 'Generated code', chatAccepted: 'Accepted code', cueRecommended: 'Recommended code', cueAccepted: 'Accepted recommendations', other: 'Other', chartLegend: 'Chart legend', mcp: 'MCP rankings', agent: 'Enterprise agent rankings', models: 'Model call distribution', languages: 'Programming language distribution', tPlusOne: 'Analytics update follows a T+1 schedule', selected: 'Current filter: {{value}}' },
      members: {
        bulkUpload: 'Bulk upload or edit', emailAdd: 'Add by email', linkInvite: 'Invite by link',
        title: 'Members', seats: 'Total seats', occupied: 'All-product accounts used', workOccupied: 'Work accounts used', purchase: 'Buy seats', add: 'Add member', tabs: { people: 'Enterprise members', departments: 'Departments', requests: 'Applications' }, collapseTree: 'Collapse department tree', expandTree: 'Expand department tree', collapseDepartment: 'Collapse department', expandDepartment: 'Expand department', moreDepartmentActions: 'More department actions', searchDepartment: 'Search departments', newDepartment: 'New department', newDepartmentTitle: 'New department', editDepartmentTitle: 'Edit department', departmentName: 'Department name', departmentNamePlaceholder: 'Enter department name', departmentID: 'Department ID', parentDepartment: 'Parent department', editDepartmentAction: 'Edit department', addChildDepartment: 'Add child department', deleteDepartment: 'Delete department', deleteDepartmentSuccess: 'Department deleted', totalMembers: 'Total', joinedMembers: 'Joined', searchPeople: 'Search name or email', direct: 'Direct members only', accountType: 'All account types', status: 'All statuses', requestPending: 'Pending', requestRejected: 'Rejected', person: 'Member', state: 'Status', stateRules: 'View status rules', role: 'Role', type: 'Account type', joined: 'Seat joined', department: 'Department', owner: 'Admin', member: 'Member', admin: 'Super admin', active: 'Active', invited: 'Pending', suspended: 'Suspended', more: 'More actions', edit: 'Edit member', disable: 'Disable account', enable: 'Enable account', remove: 'Remove member', changeDepartment: 'Change department', reclaimAccount: 'Reclaim account', changeRole: 'Change role', switchToWorkAccount: 'Switch to a Work-only account', transferSuperAdmin: 'Transfer super admin', removeMember: 'Remove member', requestUser: 'Applicant', requestDepartment: 'Department', requestTime: 'Applied at', requestAction: 'Action', approve: 'Approve', reject: 'Reject', addTitle: 'Add member', email: 'Email address', emailPlaceholder: 'Enter member email', roleLabel: 'Member role', addSuccess: 'Invitation created', empty: 'No member data', departmentDetail: 'Manage department name, direct members, and organization hierarchy.', directMembers: 'Direct members', childDepartments: 'Child departments', monthlyRequests: 'Requests this month', editDepartment: 'Edit department', ruleInvited: 'After an invitation is sent, the member must sign in and bind the account.', ruleActive: 'Members can use enterprise resources according to their role.', ruleSuspended: 'Suspending an account immediately revokes workspace access.' },
      subscription: {
        title: 'Subscription', goManage: 'Manage subscription', plan: 'Subscription plan', current: 'Current plan', flagship: 'Flagship', active: 'Active', expiry: 'Expiry date', renew: 'Renew now', seats: 'Seats', seatHint: '1 seat → 3 account slots', addSeats: 'Buy seats', available: 'Available accounts', allAccount: 'All-product accounts', workAccount: 'Work accounts', remaining: 'Remaining', addon: 'Add-on package', notPurchased: 'Not purchased', buyAddon: 'Buy add-on package', payg: 'Usage billing', notOpen: 'Not enabled', openPayg: 'Enable usage billing', actionNotice: 'The “{{action}}” action is queued for backend integration.' },
      usage: {
        title: 'Usage', cycle: 'Subscription cycle: {{start}} to {{end}}', tabs: { board: 'Usage dashboard', detail: 'Usage details' }, overall: 'Overall usage', base: 'Base sessions', overage: 'Overage sessions', exhausted: 'Exhausted', noLimit: 'No per-member limit', adjust: 'Adjust limits', buy: 'Buy add-on', noPackage: 'No add-on package purchased', people: 'People usage', searchPeople: 'Search member name or email', allMembers: 'All members', allAccounts: 'All account types', overageFilter: 'Overage usage', departments: 'Department usage', searchDepartment: 'Search departments', detailDate: 'Date', detailPerson: 'Member', detailAccount: 'Account type', detailRequests: 'Requests', detailTokens: 'Token usage', detailCost: 'Cost', detailStatus: 'Status', detailEmpty: 'No usage details', limitTitle: 'Adjust per-member limit', limitHint: 'The limit applies to the current enterprise workspace.', limitPlaceholder: 'Enter a limit', buyTitle: 'Buy add-on package', buyHint: 'Demo state: the real purchase flow will be connected later.', perMemberLimit: 'Per-member limit', selectAll: 'Select all', name: 'Name', department: 'Department', periodTotal: 'Current period total (CNY)', baseAmount: 'Base session usage (CNY)', overageAmount: 'Overage session usage (CNY)', operation: 'Action', detailAction: 'Usage details', quotaAction: 'Edit quota', chooseMember: 'Select member', today: 'Today', last7: 'Last 7 days', last30: 'Last 30 days', custom: 'Custom', dateRange: 'Select date range', download: 'Download', downloadSuccess: 'Downloaded', pagination: 'Pagination', previousPage: 'Previous page', nextPage: 'Next page', rowsPerPage: 'Rows per page', rowsUnit: 'rows/page', client: 'Client', model: 'TRAE built-in model', session: 'Session ID', tokensConsumed: 'Token usage', costConsumed: 'Amount used', modelCalls: 'Model calls', source: 'Usage source', discounted: 'After discount' },
      usageFilters: { quotaMembers: 'Members with individual quota', baseLabel: 'Base session usage', all: 'All', normal: 'Normal  Below 90%', warning: 'Warning  Between 90% and 100%', exhausted: 'Exhausted  At 100%' },
      audit: {
        title: 'Operation log', export: 'Export operation log', type: 'All operation types', operator: 'Select operator', date: 'Select time range', time: 'Time', action: 'Action', detail: 'Details', result: 'Result', ip: 'IP address', success: 'Success', failed: 'Failed', view: 'View details', empty: 'No operation logs', detailTitle: 'Operation details', detailOperator: 'Operator', detailTarget: 'Target', detailRequest: 'Request ID', close: 'Close' },
    },
  },
} as const
