export const traeEnterpriseResources = {
  'zh-CN': {
    traeEnterprise: {
      nav: { group: '企业管理（新版）', analysis: '数据分析', members: '人员管理', subscription: '订阅管理', usage: '用量管理', audit: '操作日志' },
      common: { breadcrumb: '企业管理', select: '请选择', search: '搜索', export: '导出', noData: '暂无数据', noDataHint: '当前筛选范围内没有可展示的数据', all: '全部', close: '关闭', confirm: '确定', cancel: '取消', save: '保存', success: '操作成功', loading: '加载中...', today: '今天', refresh: '刷新' },
      memberDialogs: { deleteDepartmentConfirmTitle: '确定删除此部门吗？', deleteDepartmentConfirmHint: '删除后，部门数据将无法恢复。', changeDepartmentHint: '确认后，对应人员（{{count}}人）的部门将全部变更至新部门。', department: '部门', learnMore: '了解详情', roleHint: '修改 {{name}} 人员角色：', roleBatchHint: '统一修改以下 {{count}} 名成员的人员角色：', roleAdmin: '管理员', roleAdminHint: '管理员可进行成员管理、查看企业账单、操作日志等、模型管理等功能', roleMember: '成员', roleMemberHint: '成员只可查看个人账单、设置个人账号', removeHint: '即将移除以下 {{count}} 名成员。移除后，账号名额将立即释放，且该成员产生的历史消耗仍计入账号额度池。' },
      departmentTable: { people: '部门人数', operation: '操作', detail: '详情', detailTitle: '部门详情', selectCurrent: '选中当前部门', selectBranch: '选择当前及全部下级', moveUp: '上移', moveDown: '下移', deleteBlockedTitle: '请先移除子部门及部门内人员', deleteBlockedHint: '请先移除所有子部门及部门内全部人员后再操作删除。' },
      analysis: {
        title: '数据分析', scope: '选择人员或部门…', allMembers: '全部人员', picker: { allPeople: '全部人员', search: '输入姓名、邮箱搜索' }, range: '时间范围', ranges: { today: '今天', '7d': '近 7 天', '30d': '近 30 天', month: '本月', custom: '自定义' }, datePresets: { last7: '近 7 天', last30: '近 30 天', last90: '近 90 天' }, export: '导出全部数据', exportSuccess: '数据已导出', loading: '正在加载企业分析数据...', people: '人员数据', total: '总计使用人员数量', activeMembersCount: '活跃人员数', totalMembersCount: '总人员数', cumulativeTokens: '累计 Token', latestDayTokens: '昨日 Token', memberUnit: '人', tokenUnit: 'Tokens', rpmUnit: 'RPM', tpmUnit: 'TPM', ide: 'IDE 使用人员数量', plugin: '插件使用人员数量', cli: 'CLI 使用人员数量', mobile: 'TRAE 移动端使用人员数量', desktop: 'TRAE Work 桌面版使用人员数量', web: 'TRAE Work 网页版使用人员数量', trend: '人员活跃度趋势', core: '核心使用数据', aiRate: 'AI 生成率', generated: 'AI 生成代码量', cue: 'CUE 推荐次数', chatTrend: '对话生成代码趋势', cueTrend: 'CUE 推荐代码趋势', chatGenerated: '生成代码量', chatAccepted: '采纳代码量', cueRecommended: '推荐代码次数', cueAccepted: '采纳代码次数', mcp: '智能体排行榜', agent: '用户使用排行榜', models: '大模型调用分布图', departments: '部门消耗分布图', noDepartments: '当前筛选范围内暂无部门用量', languages: '编程语言分布图', countSuffix: '次', chartLegend: '图表图例', compare: '较上一周期 {{value}}', overview: '核心指标', requestCount: '请求数', cachedTokens: '缓存 Token', activeMembers: '活跃人员 / 总人员', totalMembers: '总人员', successRate: '成功率', averageLatency: '平均响应时间', peakRpm: '峰值 RPM', peakTpm: '峰值 TPM', history: '历史数据', latestDataDate: '最新数据日期', latestInputTokens: '最新日输入 Token', latestOutputTokens: '最新日输出 Token', cumulativeInputTokens: '累计输入 Token', cumulativeOutputTokens: '累计输出 Token', cumulativeRequests: '累计请求数', tools: '智能体工具消费', toolName: '工具', totalTokens: 'Token 总量', currentCost: '当前周期消费', latestCost: '最新业务日消费', members: '人员用量', memberName: '人员', role: '角色', inputTokens: '输入 Token', outputTokens: '输出 Token', cost: '消费', model: '模型', modelDistribution: '模型 Token 分布', modelTrend: '模型 Token 趋势', memberModelTrend: '人员模型 Token 趋势', noTrend: '当前筛选范围内暂无趋势数据', noModels: '当前筛选范围内暂无模型用量', other: '其他', csvSection: '数据分区', csvName: '名称', csvDimension: '维度', csvValue: 'Value' },
      inviteList: { tab: '邀请列表', allStatuses: '全部状态', active: '生效中', revoked: '已停用', expired: '已过期', exhausted: '已用完', status: { active: '生效中', revoked: '已停用', expired: '已过期', exhausted: '已用完' }, method: '方式', linkMethod: '邀请链接', target: '目标', role: '角色', usage: '说明', statusLabel: '状态', action: '操作', copy: '复制', usageDetails: '使用情况', loading: '正在加载邀请列表...', empty: '暂无邀请链接', pagination: '邀请列表分页', paginationSummary: '共 {{total}} 条', createTitle: '邀请成员', createHeading: '邀请成员', createHint: '填写邀请信息后，可在已发邀请中查看状态和使用情况。', maxUses: '可使用次数', maxUsesRequired: '请输入可使用次数', expiresAt: '有效期至', targetRole: '目标角色', targetRoleRequired: '请选择目标角色', department: '所属部门', departmentPlaceholder: '请选择所属部门', departmentRequired: '请选择所属部门', roleHint: '所有者可选邀请系统角色或自定义角色；企业所有者身份不能通过邀请授予。', createButton: '生成邀请链接', creating: '生成中...', createSuccess: '邀请链接已生成', copySuccess: '邀请链接已复制', noExpiry: '无期限', usageTitle: '邀请链接使用情况', used: '已使用', available: '可用上限', noUsage: '暂无使用记录', noUsageHint: '有人通过该链接提交加入申请后，会显示在这里。' },
      members: {
        bulkUpload: '批量上传或修改', emailAdd: '邮件添加', linkInvite: '链接邀请',
 title: '人员管理', seats: '总席位数', occupied: '全端账号已占用', workOccupied: 'Work 专属账号已占用', purchase: '增购席位', add: '添加成员', tabs: { people: '企业人员', departments: '部门管理', requests: '申请列表' }, collapseTree: '收起部门树', expandTree: '展开部门树', collapseDepartment: '收起部门', expandDepartment: '展开部门', moreDepartmentActions: '更多部门操作', searchDepartment: '搜索部门', newDepartment: '新建部门', newDepartmentTitle: '新建部门', editDepartmentTitle: '编辑部门', departmentName: '部门名称', departmentNamePlaceholder: '请输入部门名称', departmentID: '部门 ID', parentDepartment: '上级部门', editDepartmentAction: '编辑部门', addChildDepartment: '添加子部门', deleteDepartment: '删除部门', deleteDepartmentSuccess: '部门已删除', totalMembers: '总人数', joinedMembers: '已加入', searchPeople: '搜索人员名称、邮箱', direct: '仅展示部门直属成员', status: '全部状态', requestPending: '待通过', requestRejected: '已拒绝', person: '人员', state: '状态', stateRules: '查看人员状态流转规则', role: '角色', type: '账号类型', joined: '加入席位时间', department: '部门', owner: '管理员', member: '成员', admin: '超级管理员', active: '正常', pending: '待审核', suspended: '冻结', more: '更多操作', edit: '编辑成员', disable: '停用账号', enable: '启用账号', remove: '移除成员', changeDepartment: '变更部门', changeRole: '修改角色', sendInvite: '发送邀请', transferSuperAdmin: '移交超级管理员', removeMember: '移除人员', selectedCount: '已选 {{count}} 人', cancelSelection: '取消选择', bulkDisabled: { protectedMember: '超级管理员仅支持由本人操作', removeProtectedMember: '超级管理员或当前登录人员不支持移除', inviteUnavailable: '仅待审核人员支持发送邀请' }, requestUser: '申请人', requestDepartment: '申请部门', requestTime: '申请时间', requestAction: '处理', approve: '通过', reject: '拒绝', addTitle: '添加成员', email: '邮箱地址', emailPlaceholder: '请输入成员邮箱', roleLabel: '成员角色', addSuccess: '成员邀请已创建', empty: '暂无成员数据', departmentDetail: '管理部门名称、直属成员和组织层级。', directMembers: '直属成员', childDepartments: '下级部门', monthlyRequests: '本月请求', editDepartment: '编辑部门', rulePending: '成员账号正在等待审核。', ruleActive: '成员可以按照角色权限使用企业资源。', ruleSuspended: '账号冻结后会立即撤销工作空间访问权限。' },
      joinRequests: { allStatuses: '全部状态', pending: '待审核', approved: '已通过', rejected: '已拒绝', withdrawn: '已撤回', status: { pending: '待审核', approved: '已通过', rejected: '已拒绝', withdrawn: '已撤回' }, applicant: '申请人', application: '申请信息', appliedAt: '申请时间', action: '处理', search: '搜索人员名称、邮箱', loading: '正在加载申请列表...', empty: '当前筛选范围内暂无加入申请', pagination: '申请列表分页', paginationSummary: '共 {{total}} 条', approve: '通过', reject: '拒绝', approveTitle: '确认通过申请', approveHint: '确定通过 {{name}} 的加入申请，并授予“{{role}}”角色吗？', rejectTitle: '拒绝加入申请', rejectHint: '请填写拒绝 {{name}} 加入企业的原因。', rejectionReason: '拒绝原因', rejectionReasonPlaceholder: '请输入拒绝原因', rejectionReasonRequired: '请输入拒绝原因', reviewing: '处理中...', approveSuccess: '申请已通过', rejectSuccess: '申请已拒绝' },
      subscription: {
        title: '订阅管理', goManage: '前往管理', plan: '订阅计划', current: '当前订阅', flagship: '旗舰版', active: '生效中', expiry: '到期时间', renew: '立即续费', seats: '席位', seatHint: '1 席位 → 3 账号名额', addSeats: '增购席位', available: '可用账号', allAccount: '全端账号', workAccount: 'Work 专属账号', remaining: '剩余', addon: '加量包', notPurchased: '暂未购买', buyAddon: '购买加量包', payg: '按量计费', notOpen: '暂未开通', openPayg: '开通按量付费', actionNotice: '已记录“{{action}}”操作，等待后端接入。' },
      usage: {
        title: '用量管理', cycle: '统计周期：{{start}} 至 {{end}}', tabs: { board: '用量看板', detail: '用量明细' }, overall: '整体用量', usedCost: '已用费用', people: '人员用量', searchPeople: '搜索人员名称、邮箱', allMembers: '全部成员', departments: '部门用量', searchDepartment: '搜索部门', detailDate: '时间', detailEmpty: '暂无用量数据', name: '姓名', department: '所属部门', operation: '操作', detailAction: '用量明细', chooseMember: '选择人员', today: '今天', last7: '近7天', last30: '近30天', custom: '自定义', download: '下载', downloadSuccess: '下载成功', pagination: '用量明细分页', memberPagination: '人员用量分页', paginationSummary: '共 {{total}} 条', model: '模型', vendor: '供应商', totalCost: '总费用', accountBalance: '账户可用余额', totalTokens: 'Token 总量', tokenUnit: 'Tokens', requestCount: '请求次数', successCount: '成功', errorCount: '失败', cancelledCount: '取消', inputTokens: '输入 Token', outputTokens: '输出 Token', cachedTokens: '缓存 Token', averageLatency: '平均延迟', allModels: '全部模型', allStatuses: '全部状态', success: '成功', error: '失败', cancelled: '已取消' },
      usageFilters: { quotaMembers: '单独配额成员', baseLabel: '基础会话用量', all: '全部', normal: '正常　用量低于 90%', warning: '预警　用量介于 90% 至 100%', exhausted: '耗尽　用量达到 100%' },
      audit: {
        title: '操作日志', description: '查询企业成员产生的操作审计记录', export: '导出当前页', exportSuccess: '操作日志已导出', type: '全部操作类型', operator: '选择操作人', date: '选择时间范围', time: '操作时间', action: '操作类型', detail: '操作详情', record: '操作记录', status: '操作状态', result: '结果', ip: 'IP 地址', success: '成功', failed: '失败', view: '查看详情', loading: '正在加载操作日志...', empty: '暂无操作日志', emptyHint: '当前筛选范围内没有企业操作记录。', detailTitle: '操作详情', detailOperator: '操作人', detailTarget: '操作对象', detailRequest: 'Request ID', before: '变更前', after: '变更后', pagination: '操作日志分页', paginationSummary: '共 {{total}} 条', close: '关闭' },
    },
  },
  'en-US': {
    traeEnterprise: {
      nav: { group: 'Enterprise (new)', analysis: 'Data analysis', members: 'Members', subscription: 'Subscription', usage: 'Usage', audit: 'Operation log' },
      common: { breadcrumb: 'Enterprise', select: 'Select', search: 'Search', export: 'Export', noData: 'No data', noDataHint: 'No data is available for the current filters.', all: 'All', close: 'Close', confirm: 'Confirm', cancel: 'Cancel', save: 'Save', success: 'Action completed', loading: 'Loading...', today: 'Today', refresh: 'Refresh' },
      memberDialogs: { deleteDepartmentConfirmTitle: 'Delete this department?', deleteDepartmentConfirmHint: 'This action cannot be undone.', changeDepartmentHint: 'After confirmation, the department for the {{count}} member(s) will be changed to the new department.', department: 'Department', learnMore: 'Learn more', roleHint: 'Change {{name}}\'s role:', roleBatchHint: 'Change the role for these {{count}} members:', roleAdmin: 'Admin', roleAdminHint: 'Admins can manage members, view enterprise billing and operation logs, and manage models.', roleMember: 'Member', roleMemberHint: 'Members can only view personal billing and manage their own account.', removeHint: 'You are about to remove {{count}} member(s). Their account slots will be released immediately, while historical usage will remain charged to the account quota pool.' },
      departmentTable: { people: 'People', operation: 'Actions', detail: 'Details', detailTitle: 'Department details', selectCurrent: 'Select current department', selectBranch: 'Select department and all children', moveUp: 'Move up', moveDown: 'Move down', deleteBlockedTitle: 'Remove child departments and members first', deleteBlockedHint: 'Remove all child departments and members before deleting this department.' },
      analysis: {
        title: 'Data analysis', scope: 'Select a member or department…', allMembers: 'All members', picker: { allPeople: 'All people', search: 'Search name or email' }, range: 'Time range', ranges: { today: 'Today', '7d': 'Last 7 days', '30d': 'Last 30 days', month: 'This month', custom: 'Custom' }, datePresets: { last7: 'Last 7 days', last30: 'Last 30 days', last90: 'Last 90 days' }, export: 'Export all data', exportSuccess: 'Data exported', loading: 'Loading enterprise analytics...', people: 'People data', total: 'Total active people', activeMembersCount: 'Active members', totalMembersCount: 'Total members', cumulativeTokens: 'Cumulative tokens', latestDayTokens: 'Yesterday tokens', memberUnit: 'people', tokenUnit: 'tokens', rpmUnit: 'RPM', tpmUnit: 'TPM', ide: 'IDE active people', plugin: 'Plugin active people', cli: 'CLI active people', mobile: 'TRAE mobile active people', desktop: 'TRAE Work desktop active people', web: 'TRAE Work web active people', trend: 'People activity trend', core: 'Core usage data', aiRate: 'AI generation rate', generated: 'AI generated code', cue: 'CUE recommendations', chatTrend: 'Chat generated code trend', cueTrend: 'CUE recommended code trend', chatGenerated: 'Generated code', chatAccepted: 'Accepted code', cueRecommended: 'Recommended code', cueAccepted: 'Accepted recommendations', mcp: 'Agent rankings', agent: 'User usage rankings', models: 'Model call distribution', departments: 'Department consumption distribution', noDepartments: 'No department usage is available for the current filters.', languages: 'Programming language distribution', countSuffix: 'uses', chartLegend: 'Chart legend', compare: '{{value}} vs previous period', overview: 'Core metrics', requestCount: 'Requests', cachedTokens: 'Cached tokens', activeMembers: 'Active / total members', totalMembers: 'Total members', successRate: 'Success rate', averageLatency: 'Average latency', peakRpm: 'Peak RPM', peakTpm: 'Peak TPM', history: 'Historical data', latestDataDate: 'Latest data date', latestInputTokens: 'Latest-day input tokens', latestOutputTokens: 'Latest-day output tokens', cumulativeInputTokens: 'Cumulative input tokens', cumulativeOutputTokens: 'Cumulative output tokens', cumulativeRequests: 'Cumulative requests', tools: 'Agent tool usage', toolName: 'Tool', totalTokens: 'Total tokens', currentCost: 'Period cost', latestCost: 'Latest-day cost', members: 'Member usage', memberName: 'Member', role: 'Role', inputTokens: 'Input tokens', outputTokens: 'Output tokens', cost: 'Cost', model: 'Model', modelDistribution: 'Model token distribution', modelTrend: 'Model token trend', memberModelTrend: 'Member-model token trend', noTrend: 'No trend data is available for the current filters.', noModels: 'No model usage is available for the current filters.', other: 'Other', csvSection: 'Section', csvName: 'Name', csvDimension: 'Dimension', csvValue: 'Value' },
      inviteList: { tab: 'Invitation links', allStatuses: 'All statuses', active: 'Active', revoked: 'Revoked', expired: 'Expired', exhausted: 'Exhausted', status: { active: 'Active', revoked: 'Revoked', expired: 'Expired', exhausted: 'Exhausted' }, method: 'Method', linkMethod: 'Invitation link', target: 'Target', role: 'Role', usage: 'Usage', statusLabel: 'Status', action: 'Action', copy: 'Copy', usageDetails: 'Usage', loading: 'Loading invitation links...', empty: 'No invitation links', pagination: 'Invitation pagination', paginationSummary: '{{total}} items', createTitle: 'Invite members', createHeading: 'Invite members', createHint: 'Fill in the invitation details, then track status and usage in the invitation list.', maxUses: 'Available uses', maxUsesRequired: 'Enter available uses', expiresAt: 'Expires at', targetRole: 'Target role', targetRoleRequired: 'Select a target role', department: 'Department', departmentPlaceholder: 'Select a department', departmentRequired: 'Select a department', roleHint: 'Owners can invite system or custom roles; the enterprise owner role cannot be granted through an invitation.', createButton: 'Generate invitation link', creating: 'Generating...', createSuccess: 'Invitation link created', copySuccess: 'Invitation link copied', noExpiry: 'No expiry', usageTitle: 'Invitation link usage', used: 'Used', available: 'Available limit', noUsage: 'No usage records', noUsageHint: 'Completed applications through this link will appear here.' },
      members: {
        bulkUpload: 'Bulk upload or edit', emailAdd: 'Add by email', linkInvite: 'Invite by link',
        title: 'Members', seats: 'Total seats', occupied: 'All-product accounts used', workOccupied: 'Work accounts used', purchase: 'Buy seats', add: 'Add member', tabs: { people: 'Enterprise members', departments: 'Departments', requests: 'Applications' }, collapseTree: 'Collapse department tree', expandTree: 'Expand department tree', collapseDepartment: 'Collapse department', expandDepartment: 'Expand department', moreDepartmentActions: 'More department actions', searchDepartment: 'Search departments', newDepartment: 'New department', newDepartmentTitle: 'New department', editDepartmentTitle: 'Edit department', departmentName: 'Department name', departmentNamePlaceholder: 'Enter department name', departmentID: 'Department ID', parentDepartment: 'Parent department', editDepartmentAction: 'Edit department', addChildDepartment: 'Add child department', deleteDepartment: 'Delete department', deleteDepartmentSuccess: 'Department deleted', totalMembers: 'Total', joinedMembers: 'Joined', searchPeople: 'Search name or email', direct: 'Direct members only', status: 'All statuses', requestPending: 'Pending', requestRejected: 'Rejected', person: 'Member', state: 'Status', stateRules: 'View status rules', role: 'Role', type: 'Account type', joined: 'Seat joined', department: 'Department', owner: 'Admin', member: 'Member', admin: 'Super admin', active: 'Active', pending: 'Pending review', suspended: 'Frozen', more: 'More actions', edit: 'Edit member', disable: 'Disable account', enable: 'Enable account', remove: 'Remove member', changeDepartment: 'Change department', changeRole: 'Change role', sendInvite: 'Send invitation', transferSuperAdmin: 'Transfer super admin', removeMember: 'Remove member', selectedCount: '{{count}} selected', cancelSelection: 'Clear selection', bulkDisabled: { protectedMember: 'Only the super administrator can manage their own account', removeProtectedMember: 'The super administrator or signed-in member cannot be removed', inviteUnavailable: 'Invitations can only be sent to members pending review' }, requestUser: 'Applicant', requestDepartment: 'Department', requestTime: 'Applied at', requestAction: 'Action', approve: 'Approve', reject: 'Reject', addTitle: 'Add member', email: 'Email address', emailPlaceholder: 'Enter member email', roleLabel: 'Member role', addSuccess: 'Invitation created', empty: 'No member data', departmentDetail: 'Manage department name, direct members, and organization hierarchy.', directMembers: 'Direct members', childDepartments: 'Child departments', monthlyRequests: 'Requests this month', editDepartment: 'Edit department', rulePending: 'The member account is pending review.', ruleActive: 'Members can use enterprise resources according to their role.', ruleSuspended: 'A frozen account immediately loses workspace access.' },
      joinRequests: { allStatuses: 'All statuses', pending: 'Pending', approved: 'Approved', rejected: 'Rejected', withdrawn: 'Withdrawn', status: { pending: 'Pending', approved: 'Approved', rejected: 'Rejected', withdrawn: 'Withdrawn' }, applicant: 'Applicant', application: 'Application', appliedAt: 'Applied at', action: 'Action', search: 'Search name or email', loading: 'Loading applications...', empty: 'No join applications match the current filters.', pagination: 'Application pagination', paginationSummary: '{{total}} items', approve: 'Approve', reject: 'Reject', approveTitle: 'Approve application', approveHint: 'Approve {{name}} and assign the “{{role}}” role?', rejectTitle: 'Reject application', rejectHint: 'Enter a reason for rejecting {{name}}.', rejectionReason: 'Rejection reason', rejectionReasonPlaceholder: 'Enter a rejection reason', rejectionReasonRequired: 'Enter a rejection reason', reviewing: 'Processing...', approveSuccess: 'Application approved', rejectSuccess: 'Application rejected' },
      subscription: {
        title: 'Subscription', goManage: 'Manage subscription', plan: 'Subscription plan', current: 'Current plan', flagship: 'Flagship', active: 'Active', expiry: 'Expiry date', renew: 'Renew now', seats: 'Seats', seatHint: '1 seat → 3 account slots', addSeats: 'Buy seats', available: 'Available accounts', allAccount: 'All-product accounts', workAccount: 'Work accounts', remaining: 'Remaining', addon: 'Add-on package', notPurchased: 'Not purchased', buyAddon: 'Buy add-on package', payg: 'Usage billing', notOpen: 'Not enabled', openPayg: 'Enable usage billing', actionNotice: 'The “{{action}}” action is queued for backend integration.' },
      usage: {
        title: 'Usage', cycle: 'Period: {{start}} to {{end}}', tabs: { board: 'Usage dashboard', detail: 'Usage details' }, overall: 'Overall usage', usedCost: 'Used cost', people: 'People usage', searchPeople: 'Search member name or email', allMembers: 'All members', departments: 'Department usage', searchDepartment: 'Search departments', detailDate: 'Time', detailEmpty: 'No usage data', name: 'Name', department: 'Department', operation: 'Action', detailAction: 'Usage details', chooseMember: 'Select member', today: 'Today', last7: 'Last 7 days', last30: 'Last 30 days', custom: 'Custom', download: 'Download', downloadSuccess: 'Downloaded', pagination: 'Usage detail pagination', memberPagination: 'Member usage pagination', paginationSummary: '{{total}} items', model: 'Model', vendor: 'Vendor', totalCost: 'Total cost', accountBalance: 'Available balance', totalTokens: 'Total tokens', tokenUnit: 'tokens', requestCount: 'Requests', successCount: 'Success', errorCount: 'Errors', cancelledCount: 'Cancelled', inputTokens: 'Input tokens', outputTokens: 'Output tokens', cachedTokens: 'Cached tokens', averageLatency: 'Average latency', allModels: 'All models', allStatuses: 'All statuses', success: 'Success', error: 'Error', cancelled: 'Cancelled' },
      usageFilters: { quotaMembers: 'Members with individual quota', baseLabel: 'Base session usage', all: 'All', normal: 'Normal  Below 90%', warning: 'Warning  Between 90% and 100%', exhausted: 'Exhausted  At 100%' },
      audit: {
        title: 'Operation log', description: 'Review audit events created by enterprise members', export: 'Export current page', exportSuccess: 'Operation log exported', type: 'All operation types', operator: 'Select operator', date: 'Select time range', time: 'Time', action: 'Action', detail: 'Details', record: 'Record', status: 'Status', result: 'Result', ip: 'IP address', success: 'Success', failed: 'Failed', view: 'View details', loading: 'Loading operation logs...', empty: 'No operation logs', emptyHint: 'No enterprise operations match the current filters.', detailTitle: 'Operation details', detailOperator: 'Operator', detailTarget: 'Target', detailRequest: 'Request ID', before: 'Before', after: 'After', pagination: 'Operation log pagination', paginationSummary: '{{total}} items', close: 'Close' },
    },
  },
} as const
